# Generated by Django 5.1.3 on 2024-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_doutora',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.IntegerField(choices=[('M', 'Masculino'), ('F', 'Feminino')]),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
